LIBS += libutil

libutil_DIR := $(d)

libutil_SOURCES = util.cc hash.cc serialise.cc archive.cc xml-writer.cc affinity.cc

ifneq ($(HAVE_OPENSSL), 1)
libutil_SOURCES += md5.c sha1.c sha256.c
endif

libutil_LIBS = src/boost/format/libformat
