# Configuration for probot-stale - https://github.com/probot/stale
daysUntilStale: 180
daysUntilClose: false
exemptLabels:
  - "critical"
  - "never-stale"
staleLabel: "stale"
markComment: false
closeComment: false
