#! /bin/sh
if [ -e tests/test-tmp ]; then
    chmod -R u+w tests/test-tmp
    rm -rf tests/test-tmp
fi

s=$(type -p nix-shell)
exec $s release.nix -A tarball --command "
    export NIX_REMOTE=daemon
    export NIX_PATH='$NIX_PATH'
    export NIX_BUILD_SHELL=$(type -p bash)
    export c=\$configureFlags
    exec $s release.nix -A build.x86_64-linux --exclude tarball --command '
        configureFlags+=\" \$c --prefix=$(pwd)/inst --sysconfdir=$(pwd)/inst/etc\"
        return
    '" \
    "$@"
