#!/usr/bin/env bash
if [ -e tests/test-tmp ]; then
    chmod -R u+w tests/test-tmp
    rm -rf tests/test-tmp
fi

s=$(type -p nix-shell)
exec $s release.nix -A tarball --command "
    unset http_proxy
    export NIX_REMOTE=$NIX_REMOTE
    export NIX_PATH='$NIX_PATH'
    export NIX_BUILD_SHELL=$(type -p bash)
    export c=\$configureFlags
    exec $s release.nix -A build.$(if [ $(uname -s) = Darwin ]; then echo x86_64-darwin; else echo x86_64-linux; fi) --exclude tarball --command '
        configureFlags+=\" \$c --prefix=$(pwd)/inst --sysconfdir=$(pwd)/inst/etc\"
        return
    '" \
    "$@"
