SUBS = \
  src/boost/format/Makefile.new \
  src/libutil/Makefile.new \
  src/libstore/Makefile.new \
  src/libmain/Makefile.new \
  src/libexpr/Makefile.new \
  src/nix-hash/Makefile.new \
  src/nix-store/Makefile.new \
  src/nix-instantiate/Makefile.new \
  src/nix-env/Makefile.new \
  src/nix-daemon/Makefile.new \
  corepkgs/Makefile.new

GLOBAL_CXXFLAGS = -I . -I src -I src/libutil -I src/libstore -I src/libmain -I src/libexpr

include Makefile.lib

