# array_width = 60
# attr_fn_like_width = 70
# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "SameLineWhere"
# chain_width = 60
# color = "Auto"
# combine_control_expr = true
# comment_width = 80
condense_wildcard_suffixes = true
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
edition = "2024"
empty_item_single_line = false
# enum_discrim_align_threshold = 0
# error_on_line_overflow = false
# error_on_unformatted = false
# fn_args_layout = "Tall"
# fn_call_width = 60
# fn_params_layout = "Tall"
# fn_single_line = false
# force_explicit_abi = true
# force_multiline_blocks = false
# format_code_in_doc_comments = false
# doc_comment_code_block_width = 100
# format_generated_files = true
format_macro_matchers = true
# format_macro_bodies = true
# skip_macro_invocations = []
# format_strings = false
# hard_tabs = false
hex_literal_case = "Lower"
# hide_parse_errors = false
# ignore = []
imports_granularity = "Crate"
# imports_indent = "Block"
imports_layout = "HorizontalVertical"
# indent_style = "Block"
# inline_attribute_width = 0
# match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
# max_width = 100
# merge_derives = true
newline_style = "Unix"
# normalize_comments = false
# normalize_doc_attributes = false
overflow_delimited_expr = true
# remove_nested_parens = true
# reorder_impl_items = false
# reorder_imports = true
group_imports = "StdExternalCrate"
# reorder_modules = true
# required_version = "CARGO_PKG_VERSION"
# short_array_element_width_threshold = 10
# skip_children = false
# single_line_if_else_max_width = 50
# single_line_let_else_max_width = 50
# space_after_colon = true
# space_before_colon = false
spaces_around_ranges = true
# struct_field_align_threshold = 0
# struct_lit_single_line = true
# struct_lit_width = 18
# struct_variant_width = 35
# tab_spaces = 4
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
# use_small_heuristics = "Default"
use_try_shorthand = true
# where_single_line = false
# wrap_comments = false
