#!/bin/bash

testclass="FromYAMLTest"
testmethod="execYAMLTest"

if [ -z "$1" ]; then
	echo "Usage: $0 PathToYamlTestSuiteRepository"
	echo
	echo "This script processes test cases from the yaml-test-suite repository (https://github.com/yaml/yaml-test-suite) and converts them into gtest tests for 'builtins.fromYAML'."
	exit 1
fi

echo "/* Generated by $(basename $0) */"
echo
echo "#pragma once"
echo
echo

for f in "$1"/src/*.yaml; do
	testname="$(basename ${f} .yaml)"
	echo "static constexpr std::string_view T_${testname} = R\"RAW("
	cat ${f}
	echo ")RAW\";"
	echo
done

echo
echo
echo "namespace nix {"
for f in "$1"/src/*.yaml; do
	testname="$(basename ${f} .yaml)"
	[[ "${testname}" = "2SXE" ]] && echo "    /** This test case is ignored because the YAML string is parsed incorrectly by ryml, but it's a rather artificial case, which isn't valid YAML 1.3 either."
	echo "    TEST_F(${testclass}, T_${testname}) {"
	if [ "${testname}" = "565N" ]; then
		echo "        ASSERT_THROW(${testmethod}(T_${testname}),EvalError); // nix has no binary data type"
	else
		echo "        ASSERT_EQ(${testmethod}(T_${testname}),\"OK\");"
	fi
	echo "    }"
	[[ "${testname}" = "2SXE" ]] && echo "    */"
	echo
done
echo "} /* namespace nix */"
