#include <gtest/gtest.h>
#include <gmock/gmock.h>

#ifdef __linux__
#  include "nix/store/build/pasta.hh"

namespace nix {

TEST(PastaTest, ConstantsAreDefined)
{
    // Test that all pasta constants are properly defined
    EXPECT_STREQ(pasta::PASTA_NS_IFNAME, "eth0");
    EXPECT_STREQ(pasta::PASTA_HOST_IPV4, "169.254.1.1");
    EXPECT_STREQ(pasta::PASTA_CHILD_IPV4, "169.254.1.2");
}

TEST(PastaTest, RewriteResolvConfBasic)
{
    // Test basic resolv.conf rewriting
    std::string original = R"(
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
search example.com
)";

    std::string expected = R"(
# Generated by NetworkManager
search example.com
nameserver 169.254.1.1
nameserver 64:ff9b:1:4b8e:472e:a5c8:a9fe:0101
)";

    std::string result = pasta::rewriteResolvConf(original);
    EXPECT_EQ(result, expected);
}

TEST(PastaTest, RewriteResolvConfEmpty)
{
    // Test empty resolv.conf
    std::string original = "";
    std::string expected = R"(nameserver 169.254.1.1
nameserver 64:ff9b:1:4b8e:472e:a5c8:a9fe:0101
)";
    std::string result = pasta::rewriteResolvConf(original);
    EXPECT_EQ(result, expected);
}

TEST(PastaTest, RewriteResolvConfComments)
{
    // Test resolv.conf with only comments
    std::string original = R"(# This is a comment
# Another comment
)";

    std::string expected = R"(# This is a comment
# Another comment
nameserver 169.254.1.1
nameserver 64:ff9b:1:4b8e:472e:a5c8:a9fe:0101
)";
    std::string result = pasta::rewriteResolvConf(original);
    EXPECT_EQ(result, expected);
}

TEST(PastaTest, RewriteResolvConfMixed)
{
    // Test resolv.conf with various directives
    std::string original = R"(
nameserver 192.168.1.1
nameserver 2001:4860:4860::8888
domain local.lan
search local.lan corp.lan
nameserver 192.168.1.2
options ndots:1
)";

    std::string expected = R"(
domain local.lan
search local.lan corp.lan
options ndots:1
nameserver 169.254.1.1
nameserver 64:ff9b:1:4b8e:472e:a5c8:a9fe:0101
)";

    std::string result = pasta::rewriteResolvConf(original);
    EXPECT_EQ(result, expected);
}

} // namespace nix

#endif // __linux__
