version: "{build}"
os: Visual Studio 2015

environment:
  matrix:
    - generator: Visual Studio 14 2015 Win64
    - generator: Visual Studio 14 2015

configuration:
  - Release
  - Debug

clone_depth: 10
clone_folder: c:\toml11

build_script:
  - cd C:\toml11
  - mkdir build
  - cd build
  - cmake -G"%generator%" -DCMAKE_CXX_STANDARD=11 -DBOOST_ROOT=C:/Libraries/boost_1_69_0 -Dtoml11_BUILD_TEST=ON ..
  - cmake --build . --config "%configuration%"
  - file --mime-encoding tests/toml/tests/hard_example_unicode.toml

test_script:
  - ctest --build-config "%configuration%" --timeout 300 --output-on-failure
