error: cannot evaluate a function that has an argument without a value ('greeting')
       Nix attempted to evaluate a function as a top level expression; in
       this case it must have its arguments supplied either by default
       values, or passed explicitly with '--arg' or '--argstr'. See
       https://nix.dev/manual/nix/stable/language/syntax.html#functions.
       at /pwd/cli-characterisation/function-required-arg.nix:2:3:
            1| {
            2|   greeting,
             |   ^
            3| }:
