#! /usr/bin/perl -w

my $dir = shift @ARGV;
$dir || die "missing directory";
my $url = shift @ARGV;
$url || die "missing base url";

chdir $dir || die "cannot chdir to $dir";

foreach my $prebuilt (glob("*.tar.bz2")) {

    $prebuilt =~ /-([a-z0-9]+)-([a-z0-9]+).tar.bz2$/
	|| die "invalid file name: $prebuilt";

    my $pkgHash = $1;
    my $prebuiltHash = $2;

    print "regprebuilt $pkgHash $prebuiltHash\n";
    print "regurl $prebuiltHash $url/$prebuilt\n";
}
