#!/usr/bin/env bash

set -e

script=$(nix-build -A outputs.hydraJobs.installerScriptForGHA --no-out-link)
installerHash=$(echo "$script" | cut -b12-43 -)

installerURL=https://$CACHIX_NAME.cachix.org/serve/$installerHash/install

echo "::set-output name=installerURL::$installerURL"
