LIBS += libexpr

libexpr_DIR := $(d)

libexpr_SOURCES = \
  nixexpr.cc eval.cc primops.cc lexer-tab.cc parser-tab.cc \
  get-drvs.cc attr-path.cc value-to-xml.cc value-to-json.cc \
  common-opts.cc names.cc

libexpr_LIBS = libutil libstore libformat

$(d)/parser-tab.cc $(d)/parser-tab.hh: $(d)/parser.y
	bison -v -o $(libexpr_DIR)/parser-tab.cc $< -d

$(d)/lexer-tab.cc $(d)/lexer-tab.hh: $(d)/lexer.l
	flex --outfile $(libexpr_DIR)/lexer-tab.cc --header-file=$(libexpr_DIR)/lexer-tab.hh $<
