#!/usr/bin/env bash

i='nixexpr-node-types.def'
o='nixexpr-node-types.h'

[ -e "$o" ] && { echo error: output file exists: $o; exit 1; }

typeNameList=()
while read line; do
  echo "$line" | grep '^ADD_TYPE' >/dev/null || { echo "skip line: $line"; continue; }
  typeName=$(echo "$line" | sed -E 's/^ADD_TYPE\(([^)]*?)\).*$/\1/')
  typeNameList+=("$typeName")
done < "$i"

res="// this file was auto-generated by $(basename $0) from $i\n"

res+="\n"
res+="#define TYPEID(type) TYPEID_##type\n"
res+="#define TYPEIDSTR(type) TYPEIDSTR_##type\n"
res+="\n"
# fixme: STR_HELPER returns "TYPEID_ExprVar" not "15"
#res+="#define STR_HELPER(x) #x\n"
#res+="#define TYPEIDSTR(type) STR_HELPER(TYPEID_##type)\n"
# STR_HELPER: https://stackoverflow.com/questions/5459868/concatenate-int-to-string-using-c-preprocessor

res+="\n"
typeId=1
for typeName in ${typeNameList[@]}; do
  res+="#define TYPEID_$typeName $typeId\n"
  typeId=$(( $typeId + 1 ))
done

res+="\n"
typeId=1
for typeName in ${typeNameList[@]}; do
  res+="#define TYPEIDSTR_$typeName \"$typeId\"\n"
  typeId=$(( $typeId + 1 ))
done

echo -e "$res" >"$o"
echo done "$o"

