name: Backport
on:
  # Backporting requires write permissions and a pull_request_target trigger.
  # Note that we only run the steps with elevated permissions on PRs that have
  # been merged, so the merged changes are already considered trusted.
  # zizmor: ignore[dangerous-triggers]
  pull_request_target:
    types: [closed, labeled]
permissions:
  contents: read
jobs:
  backport:
    name: Backport Pull Request
    permissions:
      # for korthout/backport-action
      contents: write
      pull-requests: write
    # nixpkgs does the same https://github.com/NixOS/nixpkgs/blob/c89bab9ae1dc0fd601ff44d017a3a8dc820fc7cd/.github/workflows/backport.yml#L24
    if: github.repository_owner == 'NixOS' && github.event.pull_request.merged == true && (github.event.action != 'labeled' || startsWith(github.event.label.name, 'backport'))
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Generate GitHub App token
        id: generate-token
        # TODO: Explicitly list the required permissions.
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0 # zizmor: ignore[github-app]
        with:
          app-id: ${{ vars.CI_APP_ID }}
          private-key: ${{ secrets.CI_APP_PRIVATE_KEY }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # required to find all branches
          fetch-depth: 0
          # We really do want to checkout a merged PR to backport it.
          allow-unsafe-pr-checkout: true
          persist-credentials: true
      - name: Create backport PRs
        uses: korthout/backport-action@2e830a1d0b8269505846ddd407a70876913ad1f8 # v4.6.0
        id: backport
        with:
          # Config README: https://github.com/korthout/backport-action#backport-action
          github_token: ${{ steps.generate-token.outputs.token }}
          github_workspace: ${{ github.workspace }}
          auto_merge_enabled: true
          pull_description: |-
            Automatic backport to `${target_branch}`, triggered by a label in #${pull_number}.
