name: Hydra status
on:
  schedule:
    - cron: "12,42 * * * *"
  workflow_dispatch:
jobs:
  check_hydra_status:
    name: Check Hydra status
    if: github.repository_owner == 'NixOS'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: bash scripts/check-hydra-status.sh

