name: "Label PR"

on:
  pull_request_target:
    types: [edited, opened, synchronize, reopened]

# WARNING:
# When extending this action, be aware that $GITHUB_TOKEN allows some write
# access to the GitHub API. This means that it should not evaluate user input in
# a way that allows code injection.

permissions:
  contents: read
  pull-requests: write

jobs:
  labels:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'NixOS'
    steps:
    - uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        sync-labels: false
